### PR TITLE
Add creator-platform-all configs and update CI build system accordingly

### PR DESCRIPTION
**Pull request by abhijit-mahajani-imgtec**
Signed-off-by: Abhijit Mahajani Abhijit.Mahajani@imgtec.com

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
build all

**Comment by nikhil-zinjurde-imgtec** [comment]
was there supposed to be path of the security key to be added here in the Makefile?

**Comment by Avinash95** [comment]
approved

**Comment by nikhil-zinjurde-imgtec** [comment]
build all

**Comment by nikhil-zinjurde-imgtec** [comment]
build all

**Comment by abhijit-mahajani-imgtec** [comment]
build all

**Pull request merged**
